# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3ef70a2a5f8a59fa10063a6a1dd1436ed6e536fcff63609d90f875bae846ba0d0211a09365feaa3d71dccb8ebe43fb70c421cd6b7d940e8dbbf535e6f399c9

test:
  secret_key_base: 93b979c17ce844a5cfaee4a7db1b242ca2e1dd5c861d39152c9242a47020ded0a64f0e5f885e7ebf87b6950757d154f827d7f628eb9565d474dbf0c0e0a59309

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
